
package sofka.view;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.ResultSetRow;
import com.mysql.jdbc.Statement;
import javax.swing.table.DefaultTableModel;
import sofka.model.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;
import sofka.controller.Manned;
import sofka.controller.Shuttle;
import sofka.controller.Unmanned;

/**
 * @author Kevin Moreno.
 */
public class View extends javax.swing.JFrame {

    Conexion conn = new Conexion();
    Connection cn = conn.conectar();
    
    public View() {
        initComponents();
        showDataShuttle();
        showDataUnManned();
        showDataManned();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNameLanz = new javax.swing.JTextField();
        txtSpeedLanz = new javax.swing.JTextField();
        txtCapacityLanz = new javax.swing.JTextField();
        txtDescriptionLanz = new javax.swing.JTextField();
        txtWeightLanz = new javax.swing.JTextField();
        txtPropulsionSysLanz = new javax.swing.JTextField();
        txtTonThrustLanz = new javax.swing.JTextField();
        txtHeightLanz = new javax.swing.JTextField();
        txtPowerLanz = new javax.swing.JTextField();
        jButtonUpdate = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        txtFuelLanz = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableShuttle = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtIdNoTripulada = new javax.swing.JTextField();
        txtNameNoTripulada = new javax.swing.JTextField();
        txtSpeedNoTripulada = new javax.swing.JTextField();
        txtDescriptionNoTripulada = new javax.swing.JTextField();
        txtWeightNoTripulada = new javax.swing.JTextField();
        txtPropulsionSysNoTripulada = new javax.swing.JTextField();
        txtTonThrustNoTripulada = new javax.swing.JTextField();
        txtEnginesNoTripulada = new javax.swing.JTextField();
        jButtonUpdateNoTripulada = new javax.swing.JButton();
        jButtonRegisterNoTripulada = new javax.swing.JButton();
        txtFuelNoTripulada = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUnManned = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtIdTripulada = new javax.swing.JTextField();
        txtNameTripulada = new javax.swing.JTextField();
        txtSpeedTripulada = new javax.swing.JTextField();
        txtDescriptionTripulada = new javax.swing.JTextField();
        txtWeightTripulada = new javax.swing.JTextField();
        txtPropulsionSysTripulada = new javax.swing.JTextField();
        txtTonThrustTripulada = new javax.swing.JTextField();
        txtCapacityPeopleTripulada = new javax.swing.JTextField();
        jButtonUpdateTripulada = new javax.swing.JButton();
        jButtonRegisterTripulada = new javax.swing.JButton();
        txtFuelTripulada = new javax.swing.JTextField();
        txtOrbitaTripulada = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableManned = new javax.swing.JTable();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sofka/view/delete.png"))); // NOI18N
        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sofka/view/delete.png"))); // NOI18N
        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sofka/view/delete.png"))); // NOI18N
        jMenuItem3.setText("Eliminar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu3.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtId.setEditable(false);
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNameLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de la nave"));
        txtNameLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameLanzActionPerformed(evt);
            }
        });

        txtSpeedLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Velocidad"));
        txtSpeedLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeedLanzActionPerformed(evt);
            }
        });

        txtCapacityLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Capacidad de transporte"));
        txtCapacityLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacityLanzActionPerformed(evt);
            }
        });

        txtDescriptionLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        txtDescriptionLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionLanzActionPerformed(evt);
            }
        });

        txtWeightLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso"));
        txtWeightLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightLanzActionPerformed(evt);
            }
        });

        txtPropulsionSysLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de propulsión"));
        txtPropulsionSysLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropulsionSysLanzActionPerformed(evt);
            }
        });

        txtTonThrustLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Toneladas de empuje"));
        txtTonThrustLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTonThrustLanzActionPerformed(evt);
            }
        });

        txtHeightLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Altura"));
        txtHeightLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightLanzActionPerformed(evt);
            }
        });

        txtPowerLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Potencia (caballos de fuerza)"));
        txtPowerLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPowerLanzActionPerformed(evt);
            }
        });

        jButtonUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar"));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonRegister.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar"));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        txtFuelLanz.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de combustible"));
        txtFuelLanz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelLanzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(txtCapacityLanz)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescriptionLanz)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(txtWeightLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTonThrustLanz))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addComponent(txtSpeedLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPropulsionSysLanz))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNameLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFuelLanz, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelLayout.createSequentialGroup()
                                .addComponent(txtHeightLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPowerLanz)))
                        .addGap(14, 14, 14))))
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameLanz))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpeedLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPropulsionSysLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeightLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTonThrustLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPowerLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeightLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFuelLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCapacityLanz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescriptionLanz, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                    .addContainerGap(408, Short.MAX_VALUE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jTableShuttle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableShuttle.setComponentPopupMenu(jPopupMenu1);
        jTableShuttle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableShuttleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableShuttle);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vehiculos tipo lanzadera", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtIdNoTripulada.setEditable(false);
        txtIdNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdNoTripuladaActionPerformed(evt);
            }
        });

        txtNameNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de la nave"));
        txtNameNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameNoTripuladaActionPerformed(evt);
            }
        });

        txtSpeedNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Velocidad"));
        txtSpeedNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeedNoTripuladaActionPerformed(evt);
            }
        });

        txtDescriptionNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        txtDescriptionNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionNoTripuladaActionPerformed(evt);
            }
        });

        txtWeightNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso"));
        txtWeightNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightNoTripuladaActionPerformed(evt);
            }
        });

        txtPropulsionSysNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de propulsión"));
        txtPropulsionSysNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropulsionSysNoTripuladaActionPerformed(evt);
            }
        });

        txtTonThrustNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Toneladas de empuje"));
        txtTonThrustNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTonThrustNoTripuladaActionPerformed(evt);
            }
        });

        txtEnginesNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de motores"));
        txtEnginesNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnginesNoTripuladaActionPerformed(evt);
            }
        });

        jButtonUpdateNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar"));
        jButtonUpdateNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateNoTripuladaActionPerformed(evt);
            }
        });

        jButtonRegisterNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar"));
        jButtonRegisterNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterNoTripuladaActionPerformed(evt);
            }
        });

        txtFuelNoTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de combustible"));
        txtFuelNoTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelNoTripuladaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnginesNoTripulada)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonUpdateNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescriptionNoTripulada)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtWeightNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTonThrustNoTripulada))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtSpeedNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPropulsionSysNoTripulada))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtIdNoTripulada, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFuelNoTripulada))
                .addGap(14, 14, 14))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jButtonRegisterNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameNoTripulada))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpeedNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPropulsionSysNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeightNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTonThrustNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEnginesNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFuelNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescriptionNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jButtonUpdateNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                    .addContainerGap(408, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterNoTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );

        jTableUnManned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUnManned.setComponentPopupMenu(jPopupMenu2);
        jTableUnManned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUnMannedMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableUnManned);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 520, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Naves no tripuladas", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtIdTripulada.setEditable(false);
        txtIdTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        txtIdTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTripuladaActionPerformed(evt);
            }
        });

        txtNameTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre de la nave"));
        txtNameTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameTripuladaActionPerformed(evt);
            }
        });

        txtSpeedTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Velocidad"));
        txtSpeedTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeedTripuladaActionPerformed(evt);
            }
        });

        txtDescriptionTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        txtDescriptionTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionTripuladaActionPerformed(evt);
            }
        });

        txtWeightTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso"));
        txtWeightTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightTripuladaActionPerformed(evt);
            }
        });

        txtPropulsionSysTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de propulsión"));
        txtPropulsionSysTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPropulsionSysTripuladaActionPerformed(evt);
            }
        });

        txtTonThrustTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Toneladas de empuje"));
        txtTonThrustTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTonThrustTripuladaActionPerformed(evt);
            }
        });

        txtCapacityPeopleTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Capacidad de personas"));
        txtCapacityPeopleTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCapacityPeopleTripuladaActionPerformed(evt);
            }
        });

        jButtonUpdateTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar"));
        jButtonUpdateTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateTripuladaActionPerformed(evt);
            }
        });

        jButtonRegisterTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar"));
        jButtonRegisterTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterTripuladaActionPerformed(evt);
            }
        });

        txtFuelTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de combustible"));
        txtFuelTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFuelTripuladaActionPerformed(evt);
            }
        });

        txtOrbitaTripulada.setBorder(javax.swing.BorderFactory.createTitledBorder("Kilometros de la orbita"));
        txtOrbitaTripulada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrbitaTripuladaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtOrbitaTripulada)
                    .addComponent(txtCapacityPeopleTripulada)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonUpdateTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDescriptionTripulada)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtWeightTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTonThrustTripulada))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtSpeedTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPropulsionSysTripulada))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtIdTripulada, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFuelTripulada))
                .addGap(14, 14, 14))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jButtonRegisterTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameTripulada))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpeedTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPropulsionSysTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWeightTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTonThrustTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCapacityPeopleTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtOrbitaTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFuelTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDescriptionTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdateTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addContainerGap(408, Short.MAX_VALUE)
                    .addComponent(jButtonRegisterTripulada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );

        jTableManned.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableManned.setComponentPopupMenu(jPopupMenu3);
        jTableManned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMannedMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableManned);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 498, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Naves tripuladas", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (JOptionPane.showConfirmDialog(null,
                                   "Seguro que quiere eliminar esta nave?", "SALIR",
                                 JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
            try {
                Shuttle lanz = new Shuttle();
                lanz.setId(Integer.parseInt(txtId.getText()));
                
                // Se elimina la nave.
                if (lanz.deleteShip(lanz.getId())) {
                    JOptionPane.showMessageDialog(rootPane, "Eliminado con exito.");
                    showDataShuttle();
                    clearData();
                } else {
                    System.out.println("No se ha seleccionado la fila.");
                }
            } catch (Exception e) {
                System.out.println("Error con eliminar: " + e);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        jButtonRegister.setEnabled(true);
        jButtonUpdate.setEnabled(false);
        clearData();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jTableShuttleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableShuttleMouseClicked

        jButtonRegister.setEnabled(false);
        jButtonUpdate.setEnabled(true);

        int row = this.jTableShuttle.getSelectedRow();
        this.txtId.setText(this.jTableShuttle.getValueAt(row, 0).toString());
        this.txtNameLanz.setText(this.jTableShuttle.getValueAt(row, 1).toString());
        this.txtSpeedLanz.setText(this.jTableShuttle.getValueAt(row, 2).toString());
        this.txtWeightLanz.setText(this.jTableShuttle.getValueAt(row, 3).toString());
        this.txtPropulsionSysLanz.setText(this.jTableShuttle.getValueAt(row, 4).toString());
        this.txtTonThrustLanz.setText(this.jTableShuttle.getValueAt(row, 5).toString());
        this.txtFuelLanz.setText(this.jTableShuttle.getValueAt(row, 6).toString());
        this.txtCapacityLanz.setText(this.jTableShuttle.getValueAt(row, 7).toString());
        this.txtHeightLanz.setText(this.jTableShuttle.getValueAt(row, 8).toString());
        this.txtPowerLanz.setText(this.jTableShuttle.getValueAt(row, 9).toString());
        this.txtDescriptionLanz.setText(this.jTableShuttle.getValueAt(row, 10).toString());
    }//GEN-LAST:event_jTableShuttleMouseClicked

    private void txtFuelLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelLanzActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed

        try {
            Shuttle lanz = new Shuttle();
            // Atributos generales de la nave.
            lanz.setName(txtNameLanz.getText());
            lanz.setSpeed(Double.parseDouble(txtSpeedLanz.getText()));
            lanz.setWeight(Integer.parseInt(txtWeightLanz.getText()));
            lanz.setPropulsionSystem(txtPropulsionSysLanz.getText());
            lanz.setTonThrust(Integer.parseInt(txtTonThrustLanz.getText()));
            lanz.setFuel(txtFuelLanz.getText());
            lanz.setDescription(txtDescriptionLanz.getText());

            // Atributos específicos del tipo Lanzadera.
            lanz.setTransportCapacity(txtCapacityLanz.getText());
            lanz.setHeight(Double.parseDouble(txtHeightLanz.getText()));
            lanz.setPower(Double.parseDouble(txtPowerLanz.getText()));

            // Se crea la nave tipo lanzadera.
            if(lanz.createShip()) {
                // Mostrar datos.
                showDataShuttle();
                clearData();
            }

        } catch (Exception e) {
            System.out.println("La inserción falló, revise que ningún campo esté vacío.");
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        try {
            Shuttle lanz = new Shuttle();
            // Atributos generales de la nave.
            lanz.setId(Integer.parseInt(txtId.getText()));
            lanz.setName(txtNameLanz.getText());
            lanz.setSpeed(Double.parseDouble(txtSpeedLanz.getText()));
            lanz.setWeight(Integer.parseInt(txtWeightLanz.getText()));
            lanz.setPropulsionSystem(txtPropulsionSysLanz.getText());
            lanz.setTonThrust(Integer.parseInt(txtTonThrustLanz.getText()));
            lanz.setFuel(txtFuelLanz.getText());
            lanz.setDescription(txtDescriptionLanz.getText());

            // Atributos específicos del tipo Lanzadera.
            lanz.setTransportCapacity(txtCapacityLanz.getText());
            lanz.setHeight(Double.parseDouble(txtHeightLanz.getText()));
            lanz.setPower(Double.parseDouble(txtPowerLanz.getText()));

            if (lanz.updateShip()) {
                JOptionPane.showMessageDialog(rootPane,"Datos actualizados correctamente.");
                showDataShuttle();
            } else {
                JOptionPane.showMessageDialog(rootPane,"Error: No seleccionó fila.");
            }
        } catch (Exception e) {
            System.out.println("Error de actualización: " + e);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void txtPowerLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPowerLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPowerLanzActionPerformed

    private void txtHeightLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightLanzActionPerformed

    private void txtTonThrustLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTonThrustLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTonThrustLanzActionPerformed

    private void txtPropulsionSysLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropulsionSysLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropulsionSysLanzActionPerformed

    private void txtWeightLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightLanzActionPerformed

    private void txtDescriptionLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionLanzActionPerformed

    private void txtCapacityLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacityLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacityLanzActionPerformed

    private void txtSpeedLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeedLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeedLanzActionPerformed

    private void txtNameLanzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameLanzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameLanzActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtIdNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdNoTripuladaActionPerformed

    private void txtNameNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameNoTripuladaActionPerformed

    private void txtSpeedNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeedNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeedNoTripuladaActionPerformed

    private void txtDescriptionNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionNoTripuladaActionPerformed

    private void txtWeightNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightNoTripuladaActionPerformed

    private void txtPropulsionSysNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropulsionSysNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropulsionSysNoTripuladaActionPerformed

    private void txtTonThrustNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTonThrustNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTonThrustNoTripuladaActionPerformed

    private void txtEnginesNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnginesNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnginesNoTripuladaActionPerformed

    private void jButtonUpdateNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateNoTripuladaActionPerformed
        try {
            Unmanned unm = new Unmanned();
            // Atributos generales de la nave.
            unm.setId(Integer.parseInt(txtIdNoTripulada.getText()));
            unm.setName(txtNameNoTripulada.getText());
            unm.setSpeed(Double.parseDouble(txtSpeedNoTripulada.getText()));
            unm.setWeight(Integer.parseInt(txtWeightNoTripulada.getText()));
            unm.setPropulsionSystem(txtPropulsionSysNoTripulada.getText());
            unm.setTonThrust(Integer.parseInt(txtTonThrustNoTripulada.getText()));
            unm.setFuel(txtFuelNoTripulada.getText());
            unm.setDescription(txtDescriptionNoTripulada.getText());

            // Atributos específicos del tipo Lanzadera.
            unm.setNumberEngines(Integer.parseInt(txtEnginesNoTripulada.getText()));

            if (unm.updateShip()) {
                JOptionPane.showMessageDialog(rootPane,"Datos actualizados correctamente.");
                showDataUnManned();
            } else {
                JOptionPane.showMessageDialog(rootPane,"Error: No seleccionó fila.");
            }
        } catch (Exception e) {
            System.out.println("Error de actualización: " + e);
        }
    }//GEN-LAST:event_jButtonUpdateNoTripuladaActionPerformed

    private void jButtonRegisterNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterNoTripuladaActionPerformed
        
        
        try {
            Unmanned unm = new Unmanned();
            // Atributos generales de la nave.
            unm.setName(txtNameNoTripulada.getText());
            unm.setSpeed(Double.parseDouble(txtSpeedNoTripulada.getText()));
            unm.setWeight(Integer.parseInt(txtWeightNoTripulada.getText()));
            unm.setPropulsionSystem(txtPropulsionSysNoTripulada.getText());
            unm.setTonThrust(Integer.parseInt(txtTonThrustNoTripulada.getText()));
            unm.setFuel(txtFuelNoTripulada.getText());
            unm.setDescription(txtDescriptionNoTripulada.getText());

            // Atributos específicos del tipo No Tripulada.
            unm.setNumberEngines(Integer.parseInt(txtEnginesNoTripulada.getText()));

            // Se crea la nave tipo lanzadera.
            if(unm.createShip()) {
                // Mostrar datos.
                showDataUnManned();
                clearData();
            }

        } catch (Exception e) {
            System.out.println("La inserción falló, revise que ningún campo esté vacío.");
        }
    }//GEN-LAST:event_jButtonRegisterNoTripuladaActionPerformed

    private void txtFuelNoTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelNoTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelNoTripuladaActionPerformed

    private void jTableUnMannedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUnMannedMouseClicked
        jButtonRegisterNoTripulada.setEnabled(false);
        jButtonUpdateNoTripulada.setEnabled(true);

        int row = this.jTableUnManned.getSelectedRow();
        this.txtIdNoTripulada.setText(this.jTableUnManned.getValueAt(row, 0).toString());
        this.txtNameNoTripulada.setText(this.jTableUnManned.getValueAt(row, 1).toString());
        this.txtSpeedNoTripulada.setText(this.jTableUnManned.getValueAt(row, 2).toString());
        this.txtWeightNoTripulada.setText(this.jTableUnManned.getValueAt(row, 3).toString());
        this.txtPropulsionSysNoTripulada.setText(this.jTableUnManned.getValueAt(row, 4).toString());
        this.txtTonThrustNoTripulada.setText(this.jTableUnManned.getValueAt(row, 5).toString());
        this.txtFuelNoTripulada.setText(this.jTableUnManned.getValueAt(row, 6).toString());
        this.txtEnginesNoTripulada.setText(this.jTableUnManned.getValueAt(row, 7).toString());
        this.txtDescriptionNoTripulada.setText(this.jTableUnManned.getValueAt(row, 8).toString());
    }//GEN-LAST:event_jTableUnMannedMouseClicked

    private void txtIdTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTripuladaActionPerformed

    private void txtNameTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameTripuladaActionPerformed

    private void txtSpeedTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeedTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeedTripuladaActionPerformed

    private void txtDescriptionTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionTripuladaActionPerformed

    private void txtWeightTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWeightTripuladaActionPerformed

    private void txtPropulsionSysTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPropulsionSysTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPropulsionSysTripuladaActionPerformed

    private void txtTonThrustTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTonThrustTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTonThrustTripuladaActionPerformed

    private void txtCapacityPeopleTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCapacityPeopleTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacityPeopleTripuladaActionPerformed

    private void jButtonUpdateTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateTripuladaActionPerformed
        try {
            Manned man = new Manned();
            // Atributos generales de la nave.
            man.setId(Integer.parseInt(txtIdTripulada.getText()));
            man.setName(txtNameTripulada.getText());
            man.setSpeed(Double.parseDouble(txtSpeedTripulada.getText()));
            man.setWeight(Integer.parseInt(txtWeightTripulada.getText()));
            man.setPropulsionSystem(txtPropulsionSysTripulada.getText());
            man.setTonThrust(Integer.parseInt(txtTonThrustTripulada.getText()));
            man.setFuel(txtFuelTripulada.getText());
            man.setDescription(txtDescriptionTripulada.getText());

            // Atributos específicos del tipo Lanzadera.
            man.setCapacity(Integer.parseInt(txtCapacityPeopleTripulada.getText()));
            man.setOrbit(txtOrbitaTripulada.getText());

            if (man.updateShip()) {
                JOptionPane.showMessageDialog(rootPane,"Datos actualizados correctamente.");
                showDataManned();
            } else {
                JOptionPane.showMessageDialog(rootPane,"Error: No seleccionó fila.");
            }
        } catch (Exception e) {
            System.out.println("Error de actualización: " + e);
        }
    }//GEN-LAST:event_jButtonUpdateTripuladaActionPerformed

    private void jButtonRegisterTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterTripuladaActionPerformed
        try {
            Manned man = new Manned();
            // Atributos generales de la nave.
            man.setName(txtNameTripulada.getText());
            man.setSpeed(Double.parseDouble(txtSpeedTripulada.getText()));
            man.setWeight(Integer.parseInt(txtWeightTripulada.getText()));
            man.setPropulsionSystem(txtPropulsionSysTripulada.getText());
            man.setTonThrust(Integer.parseInt(txtTonThrustTripulada.getText()));
            man.setFuel(txtFuelTripulada.getText());
            man.setDescription(txtDescriptionTripulada.getText());

            // Atributos específicos del tipo Tripulada.
            man.setCapacity(Integer.parseInt(txtCapacityPeopleTripulada.getText()));
            man.setOrbit(txtOrbitaTripulada.getText());

            // Se crea la nave tipo lanzadera.
            if(man.createShip()) {
                // Mostrar datos.
                showDataManned();
                clearData();
            }

        } catch (Exception e) {
            System.out.println("La inserción falló, revise que ningún campo esté vacío.");
        }
    }//GEN-LAST:event_jButtonRegisterTripuladaActionPerformed

    private void txtFuelTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFuelTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFuelTripuladaActionPerformed

    private void jTableMannedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMannedMouseClicked
        jButtonRegisterTripulada.setEnabled(false);
        jButtonUpdateTripulada.setEnabled(true);

        int row = this.jTableManned.getSelectedRow();
        this.txtIdTripulada.setText(this.jTableManned.getValueAt(row, 0).toString());
        this.txtNameTripulada.setText(this.jTableManned.getValueAt(row, 1).toString());
        this.txtSpeedTripulada.setText(this.jTableManned.getValueAt(row, 2).toString());
        this.txtWeightTripulada.setText(this.jTableManned.getValueAt(row, 3).toString());
        this.txtPropulsionSysTripulada.setText(this.jTableManned.getValueAt(row, 4).toString());
        this.txtTonThrustTripulada.setText(this.jTableManned.getValueAt(row, 5).toString());
        this.txtFuelTripulada.setText(this.jTableManned.getValueAt(row, 6).toString());
        this.txtCapacityPeopleTripulada.setText(this.jTableManned.getValueAt(row, 7).toString());
        this.txtOrbitaTripulada.setText(this.jTableManned.getValueAt(row, 8).toString());
        this.txtDescriptionTripulada.setText(this.jTableManned.getValueAt(row, 9).toString());
    }//GEN-LAST:event_jTableMannedMouseClicked

    private void txtOrbitaTripuladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrbitaTripuladaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrbitaTripuladaActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jButtonRegisterNoTripulada.setEnabled(true);
        jButtonUpdateNoTripulada.setEnabled(false);
        clearData();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (JOptionPane.showConfirmDialog(null,
                                   "Seguro que quiere eliminar esta nave?", "SALIR",
                                 JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
            try {
                Unmanned unm = new Unmanned();
                unm.setId(Integer.parseInt(txtIdNoTripulada.getText()));
                
                // Se elimina la nave.
                if (unm.deleteShip(unm.getId())) {
                    JOptionPane.showMessageDialog(rootPane, "Eliminado con exito.");
                    showDataUnManned();
                    clearData();
                } else {
                    System.out.println("No se ha seleccionado la fila.");
                }
            } catch (Exception e) {
                System.out.println("Error con eliminar: " + e);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (JOptionPane.showConfirmDialog(null,
                                   "Seguro que quiere eliminar esta nave?", "SALIR",
                                 JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
            try {
                Manned man = new Manned();
                man.setId(Integer.parseInt(txtIdTripulada.getText()));
                
                // Se elimina la nave.
                if (man.deleteShip(man.getId())) {
                    JOptionPane.showMessageDialog(rootPane, "Eliminado con exito.");
                    showDataManned();
                    clearData();
                } else {
                    System.out.println("No se ha seleccionado la fila.");
                }
            } catch (Exception e) {
                System.out.println("Error con eliminar: " + e);
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jButtonRegisterTripulada.setEnabled(true);
        jButtonUpdateTripulada.setEnabled(false);
        clearData();
    }//GEN-LAST:event_jPanel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonRegisterNoTripulada;
    private javax.swing.JButton jButtonRegisterTripulada;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonUpdateNoTripulada;
    private javax.swing.JButton jButtonUpdateTripulada;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableManned;
    private javax.swing.JTable jTableShuttle;
    private javax.swing.JTable jTableUnManned;
    private javax.swing.JTextField txtCapacityLanz;
    private javax.swing.JTextField txtCapacityPeopleTripulada;
    private javax.swing.JTextField txtDescriptionLanz;
    private javax.swing.JTextField txtDescriptionNoTripulada;
    private javax.swing.JTextField txtDescriptionTripulada;
    private javax.swing.JTextField txtEnginesNoTripulada;
    private javax.swing.JTextField txtFuelLanz;
    private javax.swing.JTextField txtFuelNoTripulada;
    private javax.swing.JTextField txtFuelTripulada;
    private javax.swing.JTextField txtHeightLanz;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdNoTripulada;
    private javax.swing.JTextField txtIdTripulada;
    private javax.swing.JTextField txtNameLanz;
    private javax.swing.JTextField txtNameNoTripulada;
    private javax.swing.JTextField txtNameTripulada;
    private javax.swing.JTextField txtOrbitaTripulada;
    private javax.swing.JTextField txtPowerLanz;
    private javax.swing.JTextField txtPropulsionSysLanz;
    private javax.swing.JTextField txtPropulsionSysNoTripulada;
    private javax.swing.JTextField txtPropulsionSysTripulada;
    private javax.swing.JTextField txtSpeedLanz;
    private javax.swing.JTextField txtSpeedNoTripulada;
    private javax.swing.JTextField txtSpeedTripulada;
    private javax.swing.JTextField txtTonThrustLanz;
    private javax.swing.JTextField txtTonThrustNoTripulada;
    private javax.swing.JTextField txtTonThrustTripulada;
    private javax.swing.JTextField txtWeightLanz;
    private javax.swing.JTextField txtWeightNoTripulada;
    private javax.swing.JTextField txtWeightTripulada;
    // End of variables declaration//GEN-END:variables

    private void showDataShuttle() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Velocidad");
        model.addColumn("Peso");
        model.addColumn("Sistema Propulsión");
        model.addColumn("Ton. Empuje");
        model.addColumn("Combustible");
        model.addColumn("Capacidad de transporte");
        model.addColumn("Altura");
        model.addColumn("Caballos de fuerza");
        model.addColumn("Descripción");
        
        // Se establece el modelo de la tabla de nave tipo Lanzadera.
        jTableShuttle.setModel(model);
        String sql = "SELECT idship, name, speed, weight, propulsion_system, ton_thrust, fuel, transport_capacity,";
               sql += "height, power, description FROM SOFKA.SHIP SP INNER JOIN SOFKA.SHUTTLE ST ON SP.IDSHIP = ST.SHIP_IDSHIP";
        String data[] = new String[11];
        
        Statement statement;
        try {
            statement = (Statement) cn.createStatement();
            // Se importa la libreria: import java.sql.* para que funcione el ResultSet.
            ResultSet result = statement.executeQuery(sql);
            
            while (result.next()) {
                data[0] = result.getString(1);
                data[1] = result.getString(2);
                data[2] = result.getString(3);
                data[3] = result.getString(4);
                data[4] = result.getString(5);
                data[5] = result.getString(6);
                data[6] = result.getString(7);
                data[7] = result.getString(8);
                data[8] = result.getString(9);
                data[9] = result.getString(10);
                data[10] = result.getString(11);
                
                model.addRow(data);
            }
            
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    private void showDataUnManned() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Velocidad");
        model.addColumn("Peso");
        model.addColumn("Sistema Propulsión");
        model.addColumn("Ton. Empuje");
        model.addColumn("Combustible");
        
        model.addColumn("Número de motores");
        model.addColumn("Descripción");
        
        // Se establece el modelo de la tabla de nave tipo Lanzadera.
        jTableUnManned.setModel(model);
        String sql =  "SELECT idship, name, speed, weight, propulsion_system, ton_thrust, fuel, number_engines, description ";
               sql += "FROM SOFKA.SHIP SP INNER JOIN SOFKA.UNMANNED ST ON SP.IDSHIP = ST.SHIP_IDSHIP;";
        String data[] = new String[9];
        
        Statement statement;
        try {
            statement = (Statement) cn.createStatement();
            // Se importa la libreria: import java.sql.* para que funcione el ResultSet.
            ResultSet result = statement.executeQuery(sql);
            
            while (result.next()) {
                data[0] = result.getString(1);
                data[1] = result.getString(2);
                data[2] = result.getString(3);
                data[3] = result.getString(4);
                data[4] = result.getString(5);
                data[5] = result.getString(6);
                data[6] = result.getString(7);
                data[7] = result.getString(8);
                data[8] = result.getString(9);
                
                model.addRow(data);
            }
            
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }
    
    private void showDataManned() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nombre");
        model.addColumn("Velocidad");
        model.addColumn("Peso");
        model.addColumn("Sistema Propulsión");
        model.addColumn("Ton. Empuje");
        model.addColumn("Combustible");
        
        model.addColumn("Capacidad de personas");
        model.addColumn("Orbita");
        
        model.addColumn("Descripción");
        
        // Se establece el modelo de la tabla de nave tipo Lanzadera.
        jTableManned.setModel(model);
        String sql = "SELECT idship, name, speed, weight, propulsion_system, ton_thrust, fuel, capacity, orbit, description ";
               sql += "FROM SOFKA.SHIP SP INNER JOIN SOFKA.MANNED ST ON SP.IDSHIP = ST.SHIP_IDSHIP";
        String data[] = new String[10];
        
        Statement statement;
        try {
            statement = (Statement) cn.createStatement();
            // Se importa la libreria: import java.sql.* para que funcione el ResultSet.
            ResultSet result = statement.executeQuery(sql);
            
            while (result.next()) {
                data[0] = result.getString(1);
                data[1] = result.getString(2);
                data[2] = result.getString(3);
                data[3] = result.getString(4);
                data[4] = result.getString(5);
                data[5] = result.getString(6);
                data[6] = result.getString(7);
                data[7] = result.getString(8);
                data[8] = result.getString(9);
                data[9] = result.getString(10);
                
                model.addRow(data);
            }
            
        } catch (Exception e) {
            System.out.println("Error: " + e);
        }
    }

    private void clearData() {
        
        // Naves tipo Lanzadera.
        txtId.setText("");
        txtNameLanz.setText("");
        txtSpeedLanz.setText("");
        txtWeightLanz.setText("");
        txtPropulsionSysLanz.setText("");
        txtTonThrustLanz.setText("");
        txtFuelLanz.setText("");
        txtDescriptionLanz.setText("");
        txtCapacityLanz.setText("");
        txtHeightLanz.setText("");
        txtPowerLanz.setText("");
        
        // Naves No tripuladas.
        txtIdNoTripulada.setText("");
        txtNameNoTripulada.setText("");
        txtSpeedNoTripulada.setText("");
        txtWeightNoTripulada.setText("");
        txtPropulsionSysNoTripulada.setText("");
        txtTonThrustNoTripulada.setText("");
        txtFuelNoTripulada.setText("");
        txtDescriptionNoTripulada.setText("");
        txtEnginesNoTripulada.setText("");
        
        // Naves Tripuladas.
        txtIdTripulada.setText("");
        txtNameTripulada.setText("");
        txtSpeedTripulada.setText("");
        txtWeightTripulada.setText("");
        txtPropulsionSysTripulada.setText("");
        txtTonThrustTripulada.setText("");
        txtFuelTripulada.setText("");
        txtDescriptionTripulada.setText("");
        txtCapacityPeopleTripulada.setText("");
        txtOrbitaTripulada.setText("");
    }
}
